### ISSUE TITLE
Show all non-zero decimal digits

### ISSUE THREAD

**Issue by aesedepece** [drcpu-github/witnet-explorer-frontend#6]
Check out this transaction:

- UI: https://witnet.network/search/1014de7c57dda3bf9def5e0f852e66832b3f4e9528223f267358e0c86e15f273
- API: https://witnet.network/api/hash?value=1014de7c57dda3bf9def5e0f852e66832b3f4e9528223f267358e0c86e15f273

The API shows the actual value for the first output (`0.12321421`), but the UI only shows 2 decimal digits (`0.12321`).

While there could be some benefit in trimming and pretty printing values like that (mainly, rough consistency in the space that an output value will take up in the UI), it sort of precludes the main use case of a block explorer, which is to have a neutral and accurate view of transactions in the block chain. A user would be puzzled if they used the explorer as a "second opinion" to verify a transaction affecting their wallet, and found that the values wouldn't totally match.

Let me suggest to print all non-zero / significant decimal digits.

This may be affecting not only transaction output values, but other places where Wit values are shown.

**Comment by drcpu-github** [comment]
I disagree that the block explorer should show all decimals by default just because that is a more neutral or accurate view. Showing all decimals will significantly decrease readability while serving very little purpose in the majority of cases (and it would completely break layouts).

However, I do agree that it may be useful to be able to look at them for verification purposes (if you really want). I added an extra checkbox on the bottom of the value transfer search panel that allows you to display all values in nanoWIT (see PR #7).
